---
title: "EMT Gene Expressions"
author: "Paul Essers"
output: html_document
---
This document was compiled at `r Sys.time()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = F, fig.height=6,fig.width=12)
set.seed(1)
library(knitr)

library(ggplot2)

theme_set(theme_bw())
theme_update(strip.background = element_blank(),
             strip.text = element_text(size=12),
             axis.text = element_text(size=14),
             #axis.text.x = element_text(angle=45,vjust=0.8,hjust=1),
             axis.ticks.length = unit(0.1, "cm"),
             axis.text.x = element_blank(),
             legend.key = element_rect(fill = "white", color = "white"),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             panel.border = element_rect(colour = "white"),
             panel.background = element_blank(),
             axis.line.x = element_line(colour = "black"),
             axis.line.y = element_line(colour = "black"))

median.quartile <- function(x){
  out <- quantile(x, probs = c(0.25,0.5,0.75))
  names(out) <- c("ymin","y","ymax")
  return(out) 
}

pairwise.var.test<-function(values,groups){
  #message("no p-value adjustments are implemented!")
  groups<-factor(groups)
  p.vals<-matrix(nrow=length(levels(groups))-1,ncol=length(levels(groups))-1)
  colnames(p.vals)<-paste0("col",seq(1,length(levels(groups))-1,1))
  row.names(p.vals)<-paste0("row",seq(1,length(levels(groups))-1,1))
  for(i in 1:(length(levels(groups))-1)){
    for(j in i+1:(length(levels(groups)))){
      if(j>length(levels(groups))){break}
      # message(paste0(i,"\t",j))
      x<-values[which(groups==as.character(levels(groups)[i]))]
      y<-values[which(groups==as.character(levels(groups)[j]))]
      p.vals[j-1,i]<-var.test(x,y)$p.value
      colnames(p.vals)[i]<-as.character(levels(groups)[i])
      row.names(p.vals)[j-1]<-as.character(levels(groups)[j])
    }
    
  }
  return(p.vals)
}

```

# Introduction

Check for EMT marker expression in individual samples


# Define Groups

```{r,fig.width=4,fig.height=4}
# setwd("Scripts")
load("../OriginalData/UT-SCC.Rdata")

cutoff.mmc  <-0.25
cutoff.ola  <-0.30
phenoDat$Class<-factor(ifelse(phenoDat$MitomycinC<cutoff.mmc & phenoDat$Olaparib<cutoff.ola,"SensitiveMO",
                       ifelse(phenoDat$MitomycinC>cutoff.mmc & phenoDat$Olaparib>cutoff.ola,"Resistant",
                       ifelse(phenoDat$MitomycinC<cutoff.mmc & phenoDat$Olaparib>cutoff.ola,"SensitiveM","Undetermined"))))

# remove controls
phenoDat$Class[phenoDat$cell.lines %in% c("FANCA","FANCG","GM847")]<-"Undetermined"
# remove ambiguous cell lines
phenoDat$Class[phenoDat$cell.lines %in% c("UT-SCC-43A","UT-SCC-32","UT-SCC-8")]<-"Undetermined"

colours<-c("green","blue","red","grey")[as.numeric(phenoDat$Class)]

# This is the plot for the paper, with the undetermined cell lines left out:
colours<-c("darkgreen","blue","red","white")[as.numeric(phenoDat$Class)]
plot(NULL,ylim=c(0,1),xlim=c(0,1),xlab="mitomycin C",ylab="olaparib",main="UT-SCC lines Drug Sensitivity")
CL.numbers<-sapply(phenoDat$cell.lines,function(x){strsplit(x,"-",fixed=T)[[1]][3]})
# two cell lines overlap in the plot, offset them a little for clarity
offsetvector<-rep(0,nrow(phenoDat))
offsetvector[phenoDat$cell.lines %in% c("UT-SCC-54C","UT-SCC-15")]<-offsetvector[phenoDat$cell.lines %in% c("UT-SCC-54C","UT-SCC-45")]+c(-0.025,+0.015)
text(phenoDat$MitomycinC,phenoDat$Olaparib+offsetvector,labels=CL.numbers,cex=0.7,col=colours)
abline(h=cutoff.ola+0.01);abline(v=cutoff.mmc-0.015) # shift the line a little so it doesn't overlap with text

rm(colours,cutoff.ola,cutoff.mmc,CL.numbers,offsetvector)

phenoDat<-phenoDat[phenoDat$Class!="Undetermined",]
phenoDat$Class<-factor(phenoDat$Class,levels=c("SensitiveMO","SensitiveM","Resistant"))
expr.UTSCC<-expr.UTSCC[,phenoDat$cell.lines]
expr.UTSCC.rpkm<-expr.UTSCC.rpkm[,phenoDat$cell.lines]
expr.UTSCC.qn<-expr.UTSCC.qn[,phenoDat$cell.lines]
```

# Expression

## Single Genes

```{r}
# grep("VIM",gene_info$external_gene_id,value = T)
emt<-c("TWIST1","TWIST2","SNAI1","SNAI2","SNAI3","ZEB1","ZEB2","CDH1","VIM")

emt<-gene_info[gene_info$external_gene_id %in% emt,]

expr.emt<-as.matrix(expr.UTSCC.rpkm[emt$ensembl_gene_id,])

library(gplots)
row.names(expr.emt)<-emt$external_gene_id
hm<-heatmap.2(expr.emt,main="Cell Lines",density.info="none", trace="none", margins =c(7,7), col=redgreen(75),dendrogram="both",labCol=NULL,scale="row", ColSideColors=c("red","blue","darkgreen")[as.numeric(phenoDat$Class)])

expr.emt<-t(scale(t(expr.emt)))
emt.full<-data.frame(phenoDat[,c(2,3,16)], t(expr.emt))
library(tidyr)
emt.long<-emt.full[,-c(1,2)] %>% gather(Gene,Expression,VIM:SNAI2)


ggplot(data=emt.long, aes(x=Class, y=Expression, fill=Class)) + 
  geom_boxplot(position=position_dodge(0.9))+
  geom_point(position = position_jitter(width = 0.2))+
  #scale_y_continuous(limits=c(0,20))+
  ylab("expression") +  ggtitle("EMT Markers")+ xlab("")+
  facet_grid(. ~ Gene,scale="free")+
  scale_fill_manual(values=c("white","lightgrey","darkgrey"))
  
```

So it looks like higher expression of CDH1, VIM and maybe SNAI2 in the sensitiveM group

```{r}
library(dplyr)

cat("CDH1")
pairwise.var.test(emt.full$CDH1,emt.full$Class)
pairwise.t.test(emt.full$CDH1,emt.full$Class,p.adjust.method = "none",pool.sd=T)
means<-emt.full[,c("CDH1","Class")] %>% as.tbl %>% group_by(Class) %>% summarize(av=mean(CDH1,na.rm=T),med=median(CDH1,na.rm=T))
kable(means)

cat("VIM")
pairwise.var.test(emt.full$VIM,emt.full$Class)
pairwise.t.test(emt.full$VIM,emt.full$Class,p.adjust.method = "none",pool.sd=F)
means<-emt.full[,c("VIM","Class")] %>% as.tbl %>% group_by(Class) %>% summarize(av=mean(VIM,na.rm=T),med=median(VIM,na.rm=T))
kable(means)

cat("SNAI2")
pairwise.var.test(emt.full$SNAI2,emt.full$Class)
pairwise.t.test(emt.full$SNAI2,emt.full$Class,p.adjust.method = "none",pool.sd=T)
means<-emt.full[,c("SNAI2","Class")] %>% as.tbl %>% group_by(Class) %>% summarize(av=mean(SNAI2,na.rm=T),med=median(SNAI2,na.rm=T))
kable(means)

```



```{r sessionInfo}
#sessionInfo()
devtools::session_info()
```